name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps: 
      - name: Say hello
        run: |
          echo "Hello World!"
  display_date:
    runs-on: ubuntu-18.04
    steps:
      - name: Show current date
        run: |
          date
  list_directories:
    runs-on: ubuntu-18.04
    steps:
      - name: Show current directory
        run: |
          ls
        